kde_model:
  num_bins: 11
  sigma: 0.1
num_channels: 3
encoder:
  conv_input_channel: 3
  conv_output_channel: 16
  block1_output_channel: 32
  block1_num_layer: 1
  block2_output_channel: 64
  block2_num_layer: 1
  block3_output_channel: 128
  block3_num_layer: 1
  flatten_size: 8192
  num_features: 16
decoder:
  linear_size: 8192
  reshape_size: [128, 8, 8]
  block1_output_channel: 128
  block1_num_layer: 1
  block2_output_channel: 64
  block2_num_layer: 1
  block3_output_channel: 32
  block3_num_layer: 1
  output_channel: 3
drn:
  num_bins: 11
  hidden_q: 100
  num_layers: 2
  num_nodes: 9
  init_method: "uniform"
  init_upper_bound: 0.5
  init_lower_bound: -0.5
  output_bins:
    2
ucc_classifier: None
loss:
  alpha: 0.5
