num_channels: 3
input_shape: [28, 28, 1]
kde_model:
  num_bins: 11
  sigma: 0.1
encoder:
  conv_input_channel: 3
  conv_output_channel: 16
  block1_output_channel: 321
  block1_num_layer: 1
  block2_output_channel: 64
  block2_num_layer: 1
  block3_output_channel: 128
  block3_num_layer: 1
  flatten_size: 8192
  num_features: 10
decoder:
  linear_size: 8192
  reshape_size: [7, 7, 128]
  block1_output_channel: 64
  block1_num_layer: 1
  block2_output_channel: 32
  block2_num_layer: 1
  block3_output_channel: 16
  block3_num_layer: 1
  output_channel: 3
ucc_classifier:
  classification_model:
  fc1_output_size: 384
  fc2_output_size: 192
  dropout_rate: 0.0
  num_classes: 4
loss:
  alpha: 0.5
