num_channels: 1
input_shape: [28, 28, 1]
kde_model:
  num_bins: 11
  sigma: 0.1
encoder:
  conv_input_channel: 1
  conv_output_channel: 16
  block1_output_channel: 321
  block1_num_layer: 1
  block2_output_channel: 64
  block2_num_layer: 1
  block3_output_channel: 128
  block3_num_layer: 1
  flatten_size: 6272
  num_features: 10
decoder:
  linear_size: 6272
  reshape_size: [7, 7, 128]
  block1_output_channel: 64
  block1_num_layer: 1
  block2_output_channel: 32
  block2_num_layer: 1
  block3_output_channel: 16
  block3_num_layer: 1
  output_channel: 1
drn:
  init_method: "xavier_uniform"
  num_bins: 11
  hidden_q: 100
  num_layers: 1
  num_nodes: 10
  output_nodes: 1
  output_bins:
    4
    # when tau approaches 0, gumbel softmax behaviour samples like a categorical distribution.
ucc_classifier: None
loss:
  alpha: -1
