defaults:
  - _self_
  - model: mnist_ucc_drn.yaml
  # experiment configs allow for version control of specific hyperparameters
  - experiments: model\\mnist_ucc_drn_init.yaml
args:
  dataset: mnist
  model_dir: saved_models/
  model_name: mnist_ucc_drn
  num_instances: 32
  ucc_start: 1
  ucc_end: 4
  batch_size: 20
  num_samples_per_class: 5
  num_workers: 4
  learning_rate: 1e-3
  num_bins: 11
  num_features: 10
  train_num_steps: 1000000
  val_num_steps: 200
  save_interval: 1000
  seed: 22
