defaults:
  - _self_
  - model: camelyon_ucc_drn.yaml
  # experiment configs allow for version control of specific hyperparameters
  - experiment: null
args:
  dataset: camelyon
  model_dir: saved_models/
  model_name: camelyon_ucc_drn
  num_instances: 32
  batch_size: 32
  num_samples_per_class: 16
  num_workers: 4
  learning_rate: 1e-4
  num_bins: 11
  num_features: 16
  train_num_steps: 100000
  val_num_steps: 200
  save_interval: 1000
  patch_size: 32
  seed: 22
